### PR TITLE
Display closed vaults properly

### LINKED ISSUE #45: dapp-treasury shows closed vaults as open
## Describe the bug

After closing a vault, the manage vault UI continues to display.

## To Reproduce
1. Follow [the instructions for starting dapp-treasury](https://github.com/Agoric/dapp-treasury)
2. Open a Vault
3. Close it using the `Close out Vault` button.
4. The `Manage Vault` widget continues to display on the `Treasury` page

## Expected behavior

Since the vault has closed, the UI should reflect that and not show the `Manage Vault` button.

## Platform Environment
 - MacOS 12. Node v14.17.0
 - is there anything special/unusual about your platform?  **No**
 - what version of the Agoric-SDK are you using? **@agoric/sdk@10.0.2-150-g6412c2883**

## Additional context

Nothing relevant

## Workaround

refreshing the Treasury UI makes the obsolete vaults go away.

### LINKED ISSUE #78: UI shows declined offers forever
If you create a vault, then decline the offer in your wallet, it will show as pending forever. The UI should not show declined vaults

### LINKED ISSUE #79: Vaults show wrong state while loading
When vaults are first rendered, they briefly appear as pending wallet approval until their notifiers return data. We should show a proper loading state instead.

### LINKED ISSUE #80: Rename "Treasury" view to "Vaults"

### LINKED ISSUE #81: "Error in offer" vaults show up forever
It's useful to see these for debugging purposes, but there should be some way to hide them.

### PR DESCRIPTION
**Pull request by samsiegart**
fixes #45, fixes #78, fixes #79, fixes #80, fixes #81 

Overview of commits:

- Rename "Treasury" view to "Vaults". This is an easy enough fix so I wanted to get it in.
- Fix state/display mismanagement in vaults view. These were all kind of intertwined so I included them all at once (see linked issues for more info). I also made some responsiveness improvements to the vaults view.
- Add animation to vaults pending approval. Just to add some flare, I can take this out of the PR if we decide we don't want it.

### Loading state
loading-vault

### Pending state
(glitch at the start of the animation is fixed)
accept-offer

### Closed vaults
image
image

### CODE REVIEW

File: ui/src/components/LoadingBlocks.jsx [hunk 1]
```diff
@@ -0,0 +1,155 @@
+import React from 'react';
```
Comment (samsiegart) [inline ui/src/components/LoadingBlocks.jsx:1]: This file is purely fluff, it's just an animation

File: ui/src/contexts/Application.jsx [hunk 2]
```diff
@@ -84,14 +97,34 @@ function watchOffers(dispatch, INSTANCE_BOARD_ID) {
...
+        status,
       } of offers) {
         if (
           instanceHandleBoardId === INSTANCE_BOARD_ID &&
-          !watchedVaults.has(id) &&
           continuingInvitation === undefined // AdjustBalances and CloseVault offers use continuingInvitation
         ) {
-          watchedVaults.add(id);
-          watchVault(id, dispatch);
+          if (status === 'decline') {
```
Comment (samsiegart) [inline ui/src/contexts/Application.jsx:106]: This file depends on a lot of contracts and notifiers that would make unit testing a big challenge. I would prefer not to prioritize that over fixing other issues at this point, but I'm calling this out just in case.

**Review by michaelfig — APPROVED** [review]
LGTM (at least wrt the code)!

I haven't carefully reviewed the CSS, but trust that it's not broken.  Perhaps a screenshot or two (or a recording) would be nice to have to be able to see.

**Comment by samsiegart** [comment]
> LGTM (at least wrt the code)!
> 
> I haven't carefully reviewed the CSS, but trust that it's not broken. Perhaps a screenshot or two (or a recording) would be nice to have to be able to see.

Thanks, added some screenshots/gifs now
